docs(cn): typo & translate in mocking.md
xiaoxunyao/cn.vitest.dev pull request #378
Opened 2024-01-10 02:37 UTC by yionr

2024-01-10 02:43 UTC, yionr reviewed
line 575 need help!

2024-01-10 06:36 UTC, elonehoo requested changes

2024-01-10 06:36 UTC, elonehoo commented on guide/mocking.md
> +`vi.mock` 和原型配合的示例:
这里的 原型 是不是保留 prototype 更好呢

2024-01-10 06:36 UTC, elonehoo commented on guide/mocking.md
> +mocked() // 是一个间谍函数
间谍 是不是保留 spy 更好呢

2024-01-10 06:37 UTC, elonehoo commented
`whatever suites you from first two examples`

`前两个例子中有非常适合你的`

2024-01-10 06:41 UTC, yionr commented on guide/mocking.md
> +mocked() // 是一个间谍函数
我更多遵循你的建议吧，之前接触测试方面的概念比较少，有些点 get 不到，翻译的会比较生硬

2024-01-10 06:46 UTC, elonehoo commented on guide/mocking.md
> +mocked() // 是一个间谍函数
啊！俺只是跟你商量看看是不是保留更好

2024-01-10 06:48 UTC, elonehoo commented on guide/mocking.md
> +mocked() // 是一个间谍函数
因为 spy 这种应该算是术语，我看 jest 是貌似是这样定义的

2024-01-10 07:04 UTC, elonehoo approved these changes

2024-01-10 07:04 UTC, merged

2024-01-10 07:14 UTC, yionr commented on guide/mocking.md
> +mocked() // 是一个间谍函数
@elonehoo 作为一个测试小白，不知道怎么跟你讨论这点。就像有人给 js 的 `promise` 翻译成 `承诺` 一样。代码写惯了的人一看，可能短时间还反应不过来。但是确实刚接触的人可能不知道这该不该翻译。翻译主要还是让大家看得顺眼就好。建议整理整理把翻译指南贴到 README 上吧，一开始我没找到，后面看到 issue 里面有点讨论，但是似乎还没定下来。像 spy 这种问颗，应该找专业测试的同学请教，讨论，定下来写到指南术语表里面就好啦。这样也能不断沉淀，不然后续翻译、校对工作都会纠结于一些重复没意思的问题，对双方都不好。

2024-01-10 07:49 UTC, elonehoo commented on guide/mocking.md
> +mocked() // 是一个间谍函数
感谢！我周末去整理一下。
给你带来的任何不便，我表示歉意

2024-01-10 07:53 UTC, yionr commented on guide/mocking.md
> +mocked() // 是一个间谍函数
哪有哪有，没有你在这维护，我到现在都还没信心尝试写测试呢！感谢你的付出，为我们大大降低了门槛。我上面可能说的偏激了一点hh

2024-01-10 07:55 UTC, elonehoo commented on guide/mocking.md
> +mocked() // 是一个间谍函数
没有，确实你说的是对。我周末整理一下，我这几天摸鱼看看别人是咋定义的！

2024-01-29 08:41 UTC, elonehoo commented on guide/mocking.md
> +mocked() // 是一个间谍函数
对不起，最近年底杂事多起来，不好意思，我明天摸鱼的时候会出指南术语表，实在不好意思